name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debugging User Name
        run: echo "GitHub User Name: eLsavation"  # Debugging nama pengguna

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: eLsavation  # Username GitHub Anda
          outputs: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
